name: Build

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update readme
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn
      - name: Update Readme
        run: node build.js
      - name: push
        run: |
          git config --global user.email "chenxin.lan.76@gmail.com"
          git config --global user.name "YXL"
          git add -A
          git commit -m "Updated readme"
          git push
