name: Build

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update readme
    permissions:
      contents: write
    steps:
      - uses: YXL76/metrics@master
        with:
          config_timezone: Asia/Shanghai
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 8
          plugin_languages_aliases: "Jupyter Notebook:Jupyter"
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_analysis_timeout: 15
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          plugin_followup_archived: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: no
          plugin_notable_indepth: no
          plugin_notable_types: pull_request, issue
          plugin_reactions: yes
          plugin_reactions_details: percentage
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages-graphs, os-graphs
          plugin_wakatime_limit: 10
          plugin_rss: yes
          plugin_rss_source: https://www.douban.com/feed/people/${{ secrets.DOUBAN_UID }}/interests
          plugin_rss_limit: 10
